# Generated by Django 5.0.7 on 2025-01-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_alter_comment_id_alter_follower_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
